<? echo $this->doctype() ?>
<head>
<?php echo $this->headTitle(); ?>
<?php echo $this->headMeta(); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>

</head>
<body>
<div class="container ">
	<div class="span-23">
		<ul id="nav" class="dropdown dropdown-horizontal">
	  <li><a href="<?php echo $this->baseUrl(); ?>">Home</a></li>
	  <li><a href="<?php echo $this->url(array('module'=>'Login', 'action'=>'logout'), '', 'true'); ?>">Log Out</a></li>
	</ul>
	</div>
	<div class="span-23 prepend-top">
		<?php echo $this->layout()->content ?>
	</div>	
	</div>
<?php echo $this->partial('_javascript_bottom.phtml', array()); ?>
</body>
</html>